export const SET_THEME = "SET_THEME";

export const RESTORE_THEME = "RESTORE_THEME";

export const SET_CHANNELS = "SET_CHANNELS";

export const SET_CATEGORY = "SET_CATEGORY";

export const ADD_CACHED_BOOKS = "ADD_CACHED_BOOKS";

export const SET_CURRENT_BOOKID = "SET_CURRENT_BOOKID";

export const RESTORE_COLLECTED_BOOKS = "RESTORE_COLLECTED_BOOKS";

export const ADD_TO_BOOK_SHELF = "ADD_TO_BOOK_SHELF";

export const REMOVE_FROM_BOOK_SHELF = "REMOVE_FROM_BOOK_SHELF";

export const SORT_BOOK_ORDER = "SORT_BOOK_ORDER";

export const APPEND_NEW_CHAPTER = "APPEND_NEW_CHAPTER";

export const SET_CHAPTER_INDEX = "SET_CHAPTER_INDEX";

export const SET_RANK_LIST = "SET_RANK_LIST";

export const ADD_RANK_BOOKS = "ADD_RANK_BOOKS";

export const SET_HOT_WORDS = "SET_HOT_WORDS";

export const ADD_SEARCH_HISTORY = "ADD_SEARCH_HISTORY";

export const TOGGLE_GENDER = "TOGGLE_GENDER";

export const LOCALIZE_DATA = "LOCALIZE_DATA";

export const LOCALIZE_DATA_SUCCESS = "LOCALIZE_DATA_SUCCESS";
